theme: jekyll-theme-dinky
show_downloads: true
github:
  zip_url: https://github.com/JD2112/MA_analysis/archive/refs/heads/main.zip
  tar_url: https://github.com/JD2112/MA_analysis/archive/refs/heads/main.tar.gz
